### ISSUE TITLE
HapiJS

### ISSUE THREAD

**Issue by knownasilya** [stewartml/express-decorators#1]
I'd love to see something similar for HapiJS!

Would you mind if I created a library based off this one, but for HapiJS? Or if you are planning to, I'd be willing to contribute/test.

**Comment by knownasilya** [comment]
I couldn't wait, and started it already o.o https://github.com/knownasilya/hapi-decorators

**Comment by stewartml** [comment]
Sorry for the delay.  Looks great, thanks for your interest in the project!  I'll add a link to your project on my readme.  Since you seem to have figured this out, I'll mark this issue as closed.

Feel free to reopen if you want any input!

**Comment by knownasilya** [comment]
Do you have any aggressive plans for this addon? Just wondering what direction you want to go in, more standard decorators, or adding some custom functionality that express doesn't really have (at least not simply).
