### ISSUE TITLE
TypeScript definitions?

### ISSUE THREAD

**Issue by nmobregon** [stewartml/express-decorators#3]
Hi, typescript newbie here.
I'm trying to use the module in my nodejs+expressjs+typescript backend app and it seems I need to install the reference via tsd install to make it work. Right? Or am I missing something? 
Because when I compile my project, I get this

> app/app.ts(8,23): error TS2307: Cannot find module 'express-decorators/load'.

I fully understand this is a ES6 module, but it seems really useful for my case too.

Thanks in advance!

**Comment by stewartml** [comment]
Hi sorry for the delay.  I'm afraid I know next to nothing about typescript.

**Comment by miguelcobain** [comment]
I'm also interested in this. I'll try to take a stab and make a PR.
